Repository Senait-coding/architecture-starter, pull requests merged in 2021-09, with the labels that each got.

#2 Time schedule has added
  data/quiz.json
  data/quiz.schema.json
  package-lock.json
  planning/backlog.md
  planning/communication-plan.md
Labels: documentation

#3 Adding availability
  planning/communication-plan.md
Labels: documentation

#8 Reinaldo-README.md
  .eslintrc.json
  client/assets/wireframe.png
  planning/README.md
  planning/backlog.md
  planning/communication-plan.md
Labels: planning

#9 backlog
  planning/backlog.md
Labels: documentation

#10 Wireframe updated
  client/assets/wireframe.png
Labels: documentation

#11 first vers dev-str
  index.html
  planning/development-strategy.md
Labels: documentation

#28 Creating the questionnaire
  data/quiz.json
Labels: data

#30 adding numbers to the questions in quiz.json
  data/quiz.json
Labels: data

#31 link data json file to business logic
  client/src/business-logic/initialize-state.js
  data/numbers.json
  data/numbers.schema.json
  index.html
Labels: documentation

#29 Creating homepage (error fixed)
  .vscode/settings.json
  client/styles/index.css
  index.html
  quiz-page.html
Labels: Presentation, CSS, HTML
